"""
Django settings for Django6 project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from django.urls.base import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#�옣怨좎뿉�꽌 �젣怨듯븯�뒗 濡쒓렇�븘�썐湲곕뒫�쓣 �궗�슜�븳 �뮘 �룎�븘�삱 �럹�씠吏� �꽕�젙
#reverse() : �빐�떦 �븿�닔瑜� �샇異쒗뻽�쓣 �븣 利됱떆 urls �뙆�씪�쓣 �깘�깋�빐 url二쇱냼瑜� 李얠쓬
#reverse_lazy() : �빐�떦 �븿�닔瑜� �샇異쒗뻽�쓣 �븣 �쎒�꽌踰� �떎�뻾�씠 以�鍮꾨릺硫� urls�뙆�씪�쓣
#                �깘�깋�빐 url二쇱냼瑜� 李얠쓬
LOGOUT_REDIRECT_URL = reverse_lazy('vote:index')
#濡쒓렇�씤�씠 �슂援щ릺�뒗 湲곕뒫�쓣 鍮꾨줈洹몄씤�긽�깭濡� �젒洹쇳븷�븣 濡쒓렇�씤�븷�닔 �엳�뒗 �럹�씠吏� �꽕�젙
LOGIN_URL = reverse_lazy('customlogin:signin')
#濡쒓렇�씤 酉곕줈 濡쒓렇�씤�뿉 �꽦怨듯뻽�쓣�븣, �씠�룞�븷 URL 寃쎈줈
LOGIN_REDIRECT_URL = reverse_lazy('vote:index')

#援ш� 媛쒕컻�옄 �궗�씠�듃�뿉�꽌 諛쒓툒諛쏆� �궎�� 鍮꾨�踰덊샇
#�겢�씪�씠�뼵�듃 id
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY ='121296315813-7shm9a7hf6c8cht4637mbnid6q36qf2t.apps.googleusercontent.com'
#�겢�씪�씠�뼵�듃 蹂댁븞鍮꾨�
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='QGm5Pcmy9WPangaoey7HVQoP'

AUTHENTICATION_BACKENDS=(
    #援ш� �씤利�
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
    #援ш� 濡쒓렇�씤怨� �봽濡쒖젥�듃�쓽 User 紐⑤뜽�겢�옒�뒪�� 留ㅼ묶�븷�븣 �궗�슜
    'django.contrib.auth.backends.ModelBackend'
    )






# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u%)@j3aw+tixgs3)=!@(j22tf7fl6p1s77=3ox26ng!utsk+s+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', '.pythonanywhrere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vote',
    'customlogin',
    'social_django', #�냼�뀥濡쒓렇�씤�뿉 ���븳 �뼱�뵆由ъ��씠�뀡
    'Blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django6.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],#�뼱�뼡 �뤃�뜑�뿉 HTML�뙆�씪�쓣 ���옣�븷吏� �꽕�젙
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect'
            ],
        },
    },
]

WSGI_APPLICATION = 'Django6.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

#�뙆�씠�뜫 肄붾뱶�뿉�꽌 �뙆�씪�쓣 �젒洹쇳븷 �븣�쓽 猷⑦듃寃쎈줈
MEDIA_URL ='/uploads/'
#�뙆�씪�씠 �떎�젣濡� ���옣�릺�뒗 猷⑦듃寃쎈줈
#BASE_DIR : �봽濡쒖젥�듃媛� �깮�꽦�맂 �쐞移�
#os.path.join(寃쎈줈,寃쎈줈) : �몢 �뤃�뜑寃쎈줈瑜� 遺숈뿬以�
MEDIA_ROOT = os.path.join(BASE_DIR,'uploads')











